### ISSUE TITLE
docsify markdown table bug

### ISSUE THREAD

**Issue by lijiarui** [qhduan/wechaty-doc#8]
```markdown
| Name | Type | Description |
| --- | --- | --- |
| profile | <code>string</code> | Wechaty Name. |
| puppet | <code>PuppetName</code> \| <code>Puppet</code> | Puppet name or instance |
| puppetOptions | <code>Partial.&lt;PuppetOptions&gt;</code> | Puppet TOKEN |
| ioToken | <code>string</code> | Io TOKEN |
```

It shuld be:

| Name | Type | Description |
| --- | --- | --- |
| profile | <code>string</code> | Wechaty Name. |
| puppet | <code>PuppetName</code> \| <code>Puppet</code> | Puppet name or instance |
| puppetOptions | <code>Partial.&lt;PuppetOptions&gt;</code> | Puppet TOKEN |
| ioToken | <code>string</code> | Io TOKEN |

Docsify showed:

![image](https://user-images.githubusercontent.com/6419514/42486863-c1f3a5d8-8430-11e8-9ed0-f7fb5c56e29f.png)

**Comment by qhduan** [comment]
fixed

**Comment by lijiarui** [comment]
didn't fix, see https://qhduan.github.io/wechaty-doc/#/api/message?id=messagefrom

![image](https://user-images.githubusercontent.com/6419514/42550783-51e11916-8506-11e8-8d7d-bea6829926b9.png)

**Comment by qhduan** [comment]
The problem is docisfy don't allow empty table cell 

the code is 

```markdown
| Param | Type | Description |
| --- | --- | --- |
| textOrContactOrFile | <code>string</code> &#124; [<code>Contact</code>](/api/contact?id=top) &#124; <code>FileBox</code> | send text, Contact, or file to bot. </br> You can use [FileBox](https://wwwnpmjscom/package/file-box) to send file |
| [mention] | [<code>Contact</code>](/api/contact?id=top) &#124; [<code>Array.&lt;Contact&gt;</code>](/api/contact?id=top) |  |
```
the last cell of the last row of the table is empty

github could resolve this, but docsify not

**Comment by qhduan** [comment]
I have fixed it with an ugly hack

a2773f99be20f3f380c03f0c982c8ca43c4f1fea

**Comment by lijiarui** [comment]
good
